### ISSUE TITLE
error arises when rendering .html

### ISSUE THREAD

**Issue by vfulco** [fluentdesk/fluentcmd#5]
New to node.js world, super excited to see this project and just getting feet wet.  On Ubuntu 15.04 machine, trying to "render all" for the boilerplate richard hendriks resume.json from jsonresume.org site pops up this error.

$fluentcmd resume.json -o out/resume.all -t modern

--other error code above this--
at /home/foouser/.nvm/versions/node/v0.12.7/lib/node_modules/fluentcmd/node_modules/fluentlib/src/core/sheet.js:166:27
Generating HTML resume: out/resume.html
ERROR: Cannot read property 'toLowerCase' of undefined

TIA for any assistance.  Googled around but nothin obvious.  Looking forward to see where this project goes since I had trouble installing the jsonresume server when I tried to dockerize it and run on a remote server.

**Comment by devlinjd** [comment]
Hi Vincent, thanks for the info. If you upgrade to the [latest release][1] (`npm update -g fluentcmd` or reinstall with `npm i fluentcmd -g`) and refresh your Hendriks resume from http://registry.jsonresume.org, this should be working again. Let me know if you run into any issues.

[1]: https://github.com/fluentdesk/fluentcmd/releases/tag/v0.4.0

**Comment by vfulco** [comment]
I should add before I saw your comments, I realized I had not created an 'out' folder hence the error surfacing. I subsequently updated fluentcmd and the hendriks resume and all formats seem to render.  Have only checked pdf so far.  Will review others and then on to how themes are constructed.  Thanks very much.

**Comment by devlinjd** [comment]
Great (and you're welcome). In that case, there's a large-ish update coming tomorrow or the next day to clean up the current theme structure and allow for different templating engines (Liquid, Handlebars, Underscore, etc.). Beyond that, another 6 or 7 themes are en route in the next several days.

**Comment by vfulco** [comment]
Just a side comment, might be useful in an FAQ to state why you believe the flexibility and range of templating options are needed.
